parameters:
  - $ref: "../components/parameters/ProductIDParams.yaml"

get:
  summary: Get product by ID
  tags:
    - Product
  responses:
    "200":
      description: Product retrieved successfully
      content:
        application/json:
          schema:
            $ref: "../components/schemas/Product.yaml"
    "400":
      $ref: "../components/responses/BadRequest.yaml"
    "404":
      $ref: "../components/responses/NotFoundError.yaml"
    "500":
      $ref: "../components/responses/StandardError.yaml"

put:
  summary: Update a product by ID
  tags:
    - Product
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/schemas/ProductInput.yaml"
  responses:
    "200":
      description: Product updated successfully
      content:
        application/json:
          schema:
            $ref: "../components/schemas/Product.yaml"
    "400":
      $ref: "../components/responses/BadRequest.yaml"
    "404":
      $ref: "../components/responses/NotFoundError.yaml"
    "500":
      $ref: "../components/responses/StandardError.yaml"

delete:
  summary: Delete a product by ID
  tags:
    - Product
  responses:
    "204":
      description: Product deleted successfully (No Content)
    "400":
      $ref: "../components/responses/BadRequest.yaml"
    "404":
      $ref: "../components/responses/NotFoundError.yaml"
    "500":
      $ref: "../components/responses/StandardError.yaml"
