/products:
  get:
    summary: Obtener todos los productos
  tags:
    - Producto
  response:
    "200":
      description: Lista de productos obtenidos exitosamente
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../components/schemas/Product.yaml" # Note: Root Relative}
    "500":
      $ref: "../components/responses/StandardError.yaml" # Root Response Error 'server:500'
  post:
    summary: create new product
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../components/schemas/ProductInput.yaml"
    response:
      "201":
        description: Product created successfully
        content:
          application/json:
            schema:
              $ref: "../components/schemas/ProductInput.yaml"
      "400":
        description: Bad Request | Invalid Request
        content:
          application/json:
            schema:
              $ref: "../components/responses/BadRequest.yaml"
