/products: 
  get:
    summary: Obtener todos los productos
  tags:
    - Producto
  response:
    "200":
      description: Lista de productos obtenidos exitosamente
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../components/schemas/Product.yaml" # Note: Root Relative
    "500":
      $ref: "../components/responses/StandardError.yaml" # Root Response Error 'server:500'
