openapi: 3.1.1
info:
  title: API FIrst
  version: 1.0.0
  description: This is a my first API with OpenAPI 3.1.1
servers:
  - url: https://localhost:3000
    description: Server is running in port | Production server
paths:
  /hello:
    get:
      summary: Hello World with OpenAPI 3.1.1 | API First
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorldResponse"
