openapi: 3.1.1
info:
  title: API FIrst OpenAPi
  version: 1.1.0 # = Update Version API =
  description: This is a my first API with OpenAPI 3.1.1
servers:
  - url: http://localhost:3000/api/v1 # = Update Version PORT & API =
    description: Server is running in port | Production server

tags: 
  - name: API_v1
    description: Develop & Created API with OpenAPI Structure

paths:
  $ref: "./paths/hello.yaml"
  $ref: "./paths/user.yaml"
  $ref: "./paths/products.yaml"

components:
  schemas:
    Hello: 
      $ref: "./components/schemas/HelloWorldResponse.yaml"
    User:
      $ref: "./components/schemas/User.yaml"
    Product: 
      $ref: "./components/schemas/Product.yaml"
    ProductInput:
      $ref: "./components/schemas/ProductInput.yaml"